# Website Information
site_name: "My IT Journal"
site_author: "Anointan Balasingam"
edit_uri: "edit/main/docs"

# Repository
repo_name: banointan/myitjournal
repo_url: https://github.com/banointan/myitjournal

# Configuration
theme:
  features: 
    - navigation.instant
    - navigation.tabs
    - navigation.indexes
    - toc.follow
    - navigation.top
    # - navigation.sections
    # - navigation.expand
  name: material
  icon:
    repo: fontawesome/brands/git-alt 
    edit: material/pencil
  palette: 
  - scheme: default
    primary: black
    accent: black
    toggle:
      icon: material/weather-night      
      name: Switch to dark mode
  - scheme: slate
    primary: white
    accent: white
    toggle:
      icon: material/weather-sunny      
      name: Switch to light mode

# Page tree
nav:
  - Home: index.md
  - Tagesberichte:
    - 2023: 
      - Januar: 
        - 31.01.2023: tagesberichte/2023/januar/tb15.md
        - 30.01.2023: tagesberichte/2023/januar/tb14.md
        - 25.01.2023: tagesberichte/2023/januar/tb13.md
        - 24.01.2023: tagesberichte/2023/januar/tb12.md
        - 23.01.2023: tagesberichte/2023/januar/tb11.md
        - 18.01.2023: tagesberichte/2023/januar/tb10.md
        - 17.01.2023: tagesberichte/2023/januar/tb09.md
        - 16.01.2023: tagesberichte/2023/januar/tb08.md
    - 2022:    
      - Dezember: 
        - 27.12.2022: tagesberichte/2022/dezember/tb07.md
      - November:
        - 29.11.2022: tagesberichte/2022/november/tb06.md
        - 22.11.2022: tagesberichte/2022/november/tb05.md
        - 21.11.2022: tagesberichte/2022/november/tb04.md
        - 14.11.2022: tagesberichte/2022/november/tb03.md
        - 09.11.2022: tagesberichte/2022/november/tb02.md
        - 08.11.2022: tagesberichte/2022/november/tb01.md
  - Lernberichte: 
    - HPC:      
      - Tools: 
        - Tools Dokumentation: lernberichte/hpc/tools/lb03.md
        - Tools Installation: lernberichte/hpc/tools/lb04.md
      - Git/GitHub: 
        - Git/GitHub Dokumentation: lernberichte/hpc/git_github/lb01.md
        - Git Befehle: lernberichte/hpc/git_github/lb02.md
      - Vagrant:
        - Vagrant Dokumentaion: lernberichte/hpc/vagrant/lb05.md      
        - Vagrantfile: lernberichte/hpc/vagrant/lb06.md     
      - Server:
        - Datenbankser: lernberichte/hpc/server/lb07.md 
        - Webserver: lernberichte/hpc/server/lb08.md
        - WordPress: lernberichte/hpc/server/wordpress/lb11.md
      - SSL: 
        - SSL & SSL-Zertifikat: lernberichte/hpc/ssl/lb09.md 
        - Mit SSL verschlüsseln: lernberichte/hpc/ssl/lb10.md 
    - AI:
      - Projekt:
        - Minesweeper:
          - Minesweeper Dokumentation: lernberichte/ai/projekt/minesweeper/minesweeper.md
          - Minesweeper Code: lernberichte/ai/projekt/minesweeper/code.md
  - Über Mich: aboutme/index.md


markdown_extensions:
  - attr_list
  - md_in_html
