# Website Information
site_name: "My IT Journal"
site_author: "Anointan Balasingam"
edit_uri: "edit/main/docs"

# Repository
repo_name: banointan/myitjournal
repo_url: https://github.com/banointan/myitjournal

# Configuration
theme:
  features: 
    - navigation.instant
    - navigation.tabs
    - navigation.indexes
    - toc.follow
    - navigation.top
    # - navigation.sections
    # - navigation.expand
  name: material
  icon:
    repo: fontawesome/brands/git-alt 
    edit: material/pencil
  palette: 
  - scheme: default
    primary: black
    accent: black
    toggle:
      icon: material/weather-night      
      name: Switch to dark mode
  - scheme: slate
    primary: white
    accent: white
    toggle:
      icon: material/weather-sunny      
      name: Switch to light mode

# Page tree
nav:
  - Home: index.md
  - Security:
    - Dokumentation:
      - Webserver:
        - Apache: 
          - http/1.1 deaktivieren: security/dokumentation/webserver/apache/http-1.1-deaktivieren.md
  - Lernberichte:
    - WPS: 
        - Microsoft Intune: 
          - Intune Einstieg: lernberichte/wps/intune/theorie_intune.md
          - Intune Einrichtung: 
            - Vorbereitung: lernberichte/wps/intune/einrichtung/vorbereitung.md
            - MDM/DNS Records: lernberichte/wps/intune/einrichtung/records.md
            - Automatic Enrollment: lernberichte/wps/intune/einrichtung/auto-enrollment.md
            - Terms and Conditions: lernberichte/wps/intune/einrichtung/nutzungsbedingung.md
            - Enrollment device limit restrictions: lernberichte/wps/intune/einrichtung/enroll-device-limit.md
            - Device Enrollment Manager: lernberichte/wps/intune/einrichtung/enroll-manager.md
            - Enrollment device platform restrictions: lernberichte/wps/intune/einrichtung/platform-restrictions.md
            
        - Multiboot-Stick: lernberichte/wps/multiboot.md
    - CI:
      - Grundlagen Telekommunikation: 
        - Systemübersicht: lernberichte/ci/telekommunikation/grundlagen_telekommunikation.md
        - Geschichte:  lernberichte/ci/telekommunikation/geschichte.md
        - Akustik:  lernberichte/ci/telekommunikation/akustik.md
        - Drahtlose Kommunikation: lernberichte/ci/telekommunikation/drahtlose_kommunikation.md
        - Breitbandtechnologien: lernberichte/ci/telekommunikation/breitbandtechnologien.md
        - Übertragungssysteme: lernberichte/ci/telekommunikation/ubertragungssysteme.md  
        - Swisscom: lernberichte/ci/swisscom/geschichte.md  
        - Mobilefunknetz: lernberichte/ci/mobilefunk/mobilefunknetz.md 
      - Azure Arc Projekt:
        - Einleitung: lernberichte/ci/azure/azure_arc/azure1.md 
        - Ubuntu Server einbinden: lernberichte/ci/azure/azure_arc/ubuntu_server_einbinden.md
        - Rocky Server einbinden: lernberichte/ci/azure/azure_arc/rocky_server_einbinden.md
    - NETSEC:
      - Referenzmodell:
        - OSI: lernberichte/netsec/refmod/osi.md
        - TCP/IP: lernberichte/netsec/refmod/tcp-ip.md
        - Unterschied: lernberichte/netsec/refmod/unterschied.md
      - Layer 1: 
        - Layer 1: lernberichte/netsec/layer1/anfang.md
        - Geschichte Netzwerkkabeln: lernberichte/netsec/layer1/geschichte.md
        - Transportarten: lernberichte/netsec/layer1/transportarten.md
        - Twisted-Pair: lernberichte/netsec/layer1/twistedpair.md
        - Lizenkabel: lernberichte/netsec/layer1/lizen.md
        - Kupferkabel Anschluss: lernberichte/netsec/layer1/kupferanschluss.md
        - Glasfaser: lernberichte/netsec/layer1/glasfaser.md 
        - Glasfaser Anschluss: lernberichte/netsec/layer1/glasfaseranschluss.md
    - HPC:      
      - Tools: 
        - Tools Dokumentation: lernberichte/hpc/tools/lb03.md
        - Tools Installation: lernberichte/hpc/tools/lb04.md
      - Git/GitHub: 
        - Git/GitHub Dokumentation: lernberichte/hpc/git_github/lb01.md
        - Git Befehle: lernberichte/hpc/git_github/lb02.md
      - Vagrant:
        - Vagrant Dokumentaion: lernberichte/hpc/vagrant/lb05.md      
        - Vagrantfile: lernberichte/hpc/vagrant/lb06.md     
      - Server:
        - Datenbankser: lernberichte/hpc/server/lb07.md 
        - Webserver: lernberichte/hpc/server/lb08.md
        - WordPress: lernberichte/hpc/server/wordpress/lb11.md
      - SSL: 
        - SSL & SSL-Zertifikat: lernberichte/hpc/ssl/lb09.md 
        - Mit SSL verschlüsseln: lernberichte/hpc/ssl/lb10.md 
      - SSH: lernberichte/hpc/ssh/ssh.md 
    - AI:
      - Projekt:
        - Minesweeper:
          - Minesweeper Dokumentation: lernberichte/ai/projekt/minesweeper/minesweeper.md
          - Minesweeper Code: lernberichte/ai/projekt/minesweeper/code.md
  - Über Mich: aboutme/index.md
    #  - Galerie: aboutme/galerie.md

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
