# Website Information
site_name: "My IT Journal"
site_author: "Anointan Balasingam"
edit_uri: "edit/main/docs"

# Repository
repo_name: banointan/myitjournal
repo_url: https://github.com/banointan/myitjournal

# Configuration
theme:
  features: 
    - navigation.instant
    - navigation.tabs
    - navigation.indexes
    - toc.follow
    - navigation.top
    # - navigation.sections
    # - navigation.expand
  name: material
  icon:
    repo: fontawesome/brands/git-alt 
    edit: material/pencil
  palette: 
  - scheme: default
    primary: black
    accent: black
    toggle:
      icon: material/weather-night      
      name: Switch to dark mode
  - scheme: slate
    primary: white
    accent: white
    toggle:
      icon: material/weather-sunny      
      name: Switch to light mode

# Page tree
nav:
  - Home: index.md
  - Tagesberichte:
    - 2023:
      - oktober:
        - 13.10.2023: tagesberichte/2023/september/tb45.md
        - 10.10.2023: tagesberichte/2023/september/tb44.md
      - september:
        - 27.09.2023: tagesberichte/2023/september/tb43.md
        - 20.09.2023: tagesberichte/2023/september/tb42.md
        - 20.09.2023: tagesberichte/2023/september/tb41.md
        - 15.09.2023: tagesberichte/2023/september/tb40.md
        - 14.09.2023: tagesberichte/2023/september/tb39.md
        - 11.09.2023: tagesberichte/2023/september/tb38.md
        - 04.09.2023: tagesberichte/2023/september/tb37.md
        - 01.09.2023: tagesberichte/2023/september/tb36.md
      - Juni:
        - 21.06.2023: tagesberichte/2023/juni/tb35.md
        - 19.06.2023: tagesberichte/2023/juni/tb34.md
        - 13.06.2023: tagesberichte/2023/juni/tb33.md
        - 12.06.2023: tagesberichte/2023/juni/tb32.md
      - Mai:
        - 30.05.2023: tagesberichte/2023/mai/tb31.md
        - 29.05.2023: tagesberichte/2023/mai/tb30.md
        - 24.05.2023: tagesberichte/2023/mai/tb29.md
        - 23.05.2023: tagesberichte/2023/mai/tb28.md
        - 09.05.2023: tagesberichte/2023/mai/tb27.md
        - 08.05.2023: tagesberichte/2023/mai/tb26.md
      - April:
        - 19.04.2023: tagesberichte/2023/april/tb25.md
        - 18.04.2023: tagesberichte/2023/april/tb24.md
        - 05.04.2023: tagesberichte/2023/april/tb23.md
        - 04.04.2023: tagesberichte/2023/april/tb22.md
      - März: 
        - 08.03.2023: tagesberichte/2023/marz/tb21.md
        - 01.03.2023: tagesberichte/2023/marz/tb20.md
      - Februar:
        - 28.02.2023: tagesberichte/2023/februar/tb19.md
        - 21.02.2023: tagesberichte/2023/februar/tb18.md
        - 07.02.2023: tagesberichte/2023/februar/tb17.md
        - 06.02.2023: tagesberichte/2023/februar/tb16.md
      - Januar: 
        - 31.01.2023: tagesberichte/2023/januar/tb15.md
        - 30.01.2023: tagesberichte/2023/januar/tb14.md
        - 25.01.2023: tagesberichte/2023/januar/tb13.md
        - 24.01.2023: tagesberichte/2023/januar/tb12.md
        - 23.01.2023: tagesberichte/2023/januar/tb11.md
        - 18.01.2023: tagesberichte/2023/januar/tb10.md
        - 17.01.2023: tagesberichte/2023/januar/tb09.md
        - 16.01.2023: tagesberichte/2023/januar/tb08.md
    - 2022:    
      - Dezember: 
        - 27.12.2022: tagesberichte/2022/dezember/tb07.md
      - November:
        - 29.11.2022: tagesberichte/2022/november/tb06.md
        - 22.11.2022: tagesberichte/2022/november/tb05.md
        - 21.11.2022: tagesberichte/2022/november/tb04.md
        - 14.11.2022: tagesberichte/2022/november/tb03.md
        - 09.11.2022: tagesberichte/2022/november/tb02.md
        - 08.11.2022: tagesberichte/2022/november/tb01.md
  - Lernberichte:
    - WPS: 
        - Intune: lernberichte/wps/intune/theorie_intune.md
        - Multiboot-Stick: lernberichte/wps/multiboot.md
    - CI:
      - Grundlagen Telekommunikation: 
        - Systemübersicht: lernberichte/ci/telekommunikation/grundlagen_telekommunikation.md
        - Geschichte:  lernberichte/ci/telekommunikation/geschichte.md
        - Akustik:  lernberichte/ci/telekommunikation/akustik.md
        - Drahtlose Kommunikation: lernberichte/ci/telekommunikation/drahtlose_kommunikation.md
        - Breitbandtechnologien: lernberichte/ci/telekommunikation/breitbandtechnologien.md
        - Übertragungssysteme: lernberichte/ci/telekommunikation/ubertragungssysteme.md  
        - Swisscom: lernberichte/ci/swisscom/geschichte.md  
        - Mobilefunknetz: lernberichte/ci/mobilefunk/mobilefunknetz.md 
      - Azure Arc Projekt:
        - Einleitung: lernberichte/ci/azure/azure_arc/azure1.md 
        - Ubuntu Server einbinden: lernberichte/ci/azure/azure_arc/ubuntu_server_einbinden.md
        - Rocky Server einbinden: lernberichte/ci/azure/azure_arc/rocky_server_einbinden.md
    - NETSEC:
      - Referenzmodell:
        - OSI: lernberichte/netsec/refmod/osi.md
        - TCP/IP: lernberichte/netsec/refmod/tcp-ip.md
        - Unterschied: lernberichte/netsec/refmod/unterschied.md
      - Layer 1: 
        - Layer 1: lernberichte/netsec/layer1/anfang.md
        - Geschichte Netzwerkkabeln: lernberichte/netsec/layer1/geschichte.md
        - Transportarten: lernberichte/netsec/layer1/transportarten.md
        - Twisted-Pair: lernberichte/netsec/layer1/twistedpair.md
        - Lizenkabel: lernberichte/netsec/layer1/lizen.md
        - Kupferkabel Anschluss: lernberichte/netsec/layer1/kupferanschluss.md
        - Glasfaser: lernberichte/netsec/layer1/glasfaser.md 
        - Glasfaser Anschluss: lernberichte/netsec/layer1/glasfaseranschluss.md
    - HPC:      
      - Tools: 
        - Tools Dokumentation: lernberichte/hpc/tools/lb03.md
        - Tools Installation: lernberichte/hpc/tools/lb04.md
      - Git/GitHub: 
        - Git/GitHub Dokumentation: lernberichte/hpc/git_github/lb01.md
        - Git Befehle: lernberichte/hpc/git_github/lb02.md
      - Vagrant:
        - Vagrant Dokumentaion: lernberichte/hpc/vagrant/lb05.md      
        - Vagrantfile: lernberichte/hpc/vagrant/lb06.md     
      - Server:
        - Datenbankser: lernberichte/hpc/server/lb07.md 
        - Webserver: lernberichte/hpc/server/lb08.md
        - WordPress: lernberichte/hpc/server/wordpress/lb11.md
      - SSL: 
        - SSL & SSL-Zertifikat: lernberichte/hpc/ssl/lb09.md 
        - Mit SSL verschlüsseln: lernberichte/hpc/ssl/lb10.md 
      - SSH: lernberichte/hpc/ssh/ssh.md 
    - AI:
      - Projekt:
        - Minesweeper:
          - Minesweeper Dokumentation: lernberichte/ai/projekt/minesweeper/minesweeper.md
          - Minesweeper Code: lernberichte/ai/projekt/minesweeper/code.md
  - Über Mich: aboutme/index.md
    #  - Galerie: aboutme/galerie.md

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
