# Website Information
site_name: "My IT Journal"
site_author: "Anointan Balasingam"
edit_uri: "edit/main/docs"

# Repository
repo_name: banointan/myitjournal
repo_url: https://github.com/banointan/myitjournal



# Configuration
theme:
  features: 
    - navigation.instant
    - navigation.tabs
    - navigation.indexes
    - toc.follow
    - navigation.top


    # - navigation.sections
    # - navigation.expand
 
  name: material

  icon:
    repo: fontawesome/brands/git-alt 
    edit: material/pencil

  palette: 
  - scheme: default
    primary: black
    accent: black
    toggle:
      icon: material/weather-night      
      name: Switch to dark mode
  - scheme: slate
    primary: white
    accent: white
    toggle:
      icon: material/weather-sunny      
      name: Switch to light mode

# Page tree
nav:
  - Home: index.md
  - Tagesberichte:      
    - Dezember: 
      - 14.11.2022: tagesberichte/dezember2022/tb03.md
      - 09.11.2022: tagesberichte/dezember2022/tb02.md
      - 08.11.2022: tagesberichte/dezember2022/tb01.md

  - Lernberichte: 
    - HPC:      
      - Git/GitHub: lernberichte/hpc/git:github/lb01.md
      - Git Befehle: lernberichte/hpc/git:github/lb02.md

    - AI:
      - Projekt:
        - Minesweeper:
          - Minesweeper Dokumentation: lernberichte/ai/projekt/minesweeper/minesweeper.md
          - Minesweeper Code: lernberichte/ai/projekt/minesweeper/code.md


